### ISSUE TITLE
Gracefully handle unknown yaml keys

### ISSUE THREAD

**Issue by ahawker** [probot/settings#111]
Low priority but would be nice to get better error messages/validation when a key is mistyped.

**Example config**

```
lables:
  - name: bug
    color: CC0000
```

Accidentally mis-spelling `labels` as `lables` will cause a `Plugin is not a contructor` error.

```
2019-02-14T18:29:24.357037+00:00 app[web.1]: 18:29:24.356Z ERROR event: Plugin is not a constructor (id=734cd71c-3086-11e9-8c64-6facabd86ce3)
2019-02-14T18:29:24.357071+00:00 app[web.1]:   TypeError: Plugin is not a constructor
2019-02-14T18:29:24.357079+00:00 app[web.1]: at Promise.all.Object.entries.map (/app/node_modules/probot-settings/lib/settings.js:24:14)
2019-02-14T18:29:24.357082+00:00 app[web.1]: at Array.map (<anonymous>)
2019-02-14T18:29:24.357084+00:00 app[web.1]: at Settings.update (/app/node_modules/probot-settings/lib/settings.js:19:52)
2019-02-14T18:29:24.357086+00:00 app[web.1]: at github.repos.getContent.then.res (/app/node_modules/probot-settings/lib/settings.js:8:49)
2019-02-14T18:29:24.357089+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
```

It took me digging into the code to see what the issue was. Definitely user error but it would be helpful to handle this specific case with a better log message, e.g. `key 'foo' is not supported` or whatnot.

**Comment by justinmchase** [comment]
I just hit this issue also, can confirm a decent error message would be nice. Perhaps a validation step for the entire file schema before attempting to deserialize it?
