### ISSUE TITLE
Github Enterprise: "context.github.repos.getContents is not a function"

### ISSUE THREAD

**Issue by aegershman** [probot/settings#123]
Pushing a package.json that looks like this:

```
{
  "name": "probot-combo-value-pack",
  "private": true,
  "dependencies": {
    "probot-settings": "probot/settings",
    "probot-labeler": "probot/autolabeler"
  },
  "scripts": {
    "start": "probot run"
  },
  "engines": {
    "node": "10.x"
  },
  "probot": {
    "apps": [
      "probot-settings",
      "probot-labeler"
    ]
  }
}
```

and getting an error within `probot-config`, which says `context.github.repos.getContents` is not a function:

```log
2019-05-31T09:17:27.970-05:00 [APP/PROC/WEB/1] [OUT] at EventEmitter.events.on (/home/vcap/deps/0/node_modules/probot/lib/robot.js:102:17)
2019-05-31T09:17:27.970-05:00 [APP/PROC/WEB/1] [OUT] at robot.on (/home/vcap/deps/0/node_modules/probot-settings/index.js:9:26)
2019-05-31T09:17:27.970-05:00 [APP/PROC/WEB/1] [OUT] at getConfig (/home/vcap/deps/0/node_modules/probot-config/lib/index.js:114:24)
2019-05-31T09:17:27.970-05:00 [APP/PROC/WEB/1] [OUT] at loadYaml (/home/vcap/deps/0/node_modules/probot-config/lib/index.js:48:49)
2019-05-31T09:17:27.970-05:00 [APP/PROC/WEB/1] [OUT] [90m TypeError: context.github.repos.getContents is not a function
```

Using GitHub Enterprise Server 2.16.2

Guessing this is related to a change in an upstream dependency (probot-config, probot itself, etc.) that has deprecated one of the modules used for retrieving content within GHE.

**Comment by aegershman** [comment]
My apologies, appears things are failing entirely due to an issue with probot/autolabeler rather than settings...

But nonetheless, still seeing this:

```
2019-06-03T11:12:20.508-05:00 [APP/PROC/WEB/1] [ERR] DEPRECATED (@octokit/rest): `repos.getContent()` is deprecated, use `repos.getContents()`
2019-06-03T11:12:21.507-05:00 [APP/PROC/WEB/1] [ERR] DEPRECATED (@octokit/rest): `issues.getLabels()` is deprecated, use `issues.listLabelsForRepo()`
2019-06-03T11:12:22.501-05:00 [APP/PROC/WEB/1] [ERR] DEPRECATED (@octokit/rest): "oldname" parameter has been renamed to "current_name"
```
